### ISSUE TITLE
Intermittent error occurring in firebase-auto-ids

### ISSUE THREAD

**Issue by katowulf** [katowulf/mockfirebase#80]
This only occurs occasionally when running tests for firebase-util.

```
PhantomJS 1.9.8 (Mac OS X) failed specs:
  RecordSetEventManager > child_moved event > should not trigger a value event if initial load is not completed
	TypeError: 'undefined' is not an object (evaluating 'run.randomCharacters[i] = 0')
	    at collisionSafeCharacterIndexes (/var/folders/mz/ljn6f63x49zcm50mqqnh1kc0008m_p/T/e73829d025dc1bc31da07d605e522fe8.browserify:10296:0 <- node_modules/mockfirebase/node_modules/firebase-auto-ids/src/index.js:29:0)
	    at generateAutoId (/var/folders/mz/ljn6f63x49zcm50mqqnh1kc0008m_p/T/e73829d025dc1bc31da07d605e522fe8.browserify:10306:0 <- node_modules/mockfirebase/node_modules/firebase-auto-ids/src/index.js:39:0)
	    at /var/folders/mz/ljn6f63x49zcm50mqqnh1kc0008m_p/T/e73829d025dc1bc31da07d605e522fe8.browserify:11085:0 <- node_modules/mockfirebase/src/firebase.js:515:0
	    at /var/folders/mz/ljn6f63x49zcm50mqqnh1kc0008m_p/T/e73829d025dc1bc31da07d605e522fe8.browserify:10786:0 <- node_modules/mockfirebase/src/firebase.js:216:0
	    at /var/folders/mz/ljn6f63x49zcm50mqqnh1kc0008m_p/T/e73829d025dc1bc31da07d605e522fe8.browserify:18734:0 <- test/NormalizedCollection/RecordSetEventManager.spec.js:229:0
```

**Comment by bendrucker** [comment]
Still happening with 0.11 (just pushed)?

**Comment by katowulf** [comment]
Haven't been able to repro in 0.11. Will reopen if I see this again.
